version: "3.9"



x-database_environments: &db_env
  MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
  MYSQL_DATABASE: ${DATABASE_NAME}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
  mysql:
    restart: always
    image: mysql:5-oracle
    network_mode: "host"
    env_file:
      - .env
    environment: *db_env
    healthcheck:
      test: [ "CMD", "mysqladmin", "--password=$SQL_ROOT_PASSWORD", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  breizhsport_backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "1080:1080"
    env_file:
      - .env
    environment:
      <<: *db_env
      DATABASE_URL: mysql
      DATABASE_USE_ROOT: ${DATABASE_USE_ROOT}

    depends_on:
      mysql:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:1080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db:
#    labels:
#      - breizhsport_db_volume
